# Generated by Django 5.1.2 on 2024-12-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='NULL', max_length=100)),
                ('branch', models.CharField(default='NULL', max_length=100)),
                ('name', models.CharField(default='NULL', max_length=100)),
                ('father_name', models.CharField(default='NULL', max_length=100)),
                ('spouse_name', models.CharField(default='NULL', max_length=100)),
                ('DOB', models.CharField(default='NULL', max_length=1000)),
                ('aadhar', models.CharField(default='NULL', max_length=1000)),
                ('PAN', models.CharField(default='NULL', max_length=1000)),
                ('Address', models.CharField(default='NULL', max_length=1000)),
                ('pincode', models.CharField(default='NULL', max_length=100)),
                ('price_quoted', models.CharField(default='NULL', max_length=100)),
                ('query', models.CharField(default='NULL', max_length=1000)),
                ('Remarks', models.CharField(default='NULL', max_length=100)),
                ('Status', models.CharField(default='NULL', max_length=100)),
                ('approved', models.CharField(default='NULL', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=100)),
                ('info', models.CharField(default='NULL', max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
